const bebidas = [
    {
        nombre: "Glenfiddich 12",
        precio: 8500,
        stock: 120,
        codigo: "GF12",
        descripcion: "Un whisky escocés de malta con notas de pera y roble, suavemente afrutado y especiado.",
    },
    {
        nombre: "Macallan 18",
        precio: 32000,
        stock: 35,
        codigo: "MC18",
        descripcion: "Conocido por sus sabores profundos de frutas secas, especias y roble, madurado en barricas de jerez.",
    },
    {
        nombre: "Lagavulin 16",
        precio: 22000,
        stock: 50,
        codigo: "LV16",
        descripcion: "Un whisky de malta con un perfil de sabor ahumado y turba, con notas de frutas y especias.",
    },
    {
        nombre: "Ardbeg 10",
        precio: 13000,
        stock: 75,
        codigo: "AB10",
        descripcion: "Un whisky escocés conocido por su fuerte carácter ahumado y notas de malta dulce.",
    },
    {
        nombre: "Glenlivet 15",
        precio: 14000,
        stock: 80,
        codigo: "GL15",
        descripcion: "Ofrece un sabor equilibrado con notas de manzana verde y especias, madurado en barricas de roble.",
    },
    {
        nombre: "Highland Park 12",
        precio: 11000,
        stock: 95,
        codigo: "HP12",
        descripcion: "Un whisky con un sabor equilibrado entre el dulce y el ahumado, con notas de miel y especias.",
    },
    {
        nombre: "Balvenie DoubleWood 12",
        precio: 15500,
        stock: 40,
        codigo: "BD12",
        descripcion: "Madurado en dos tipos de barricas, aporta notas de frutas secas, especias y roble.",
    },
    {
        nombre: "Oban 14",
        precio: 18000,
        stock: 30,
        codigo: "OB14",
        descripcion: "Ofrece un perfil de sabor equilibrado con notas de sal marina, frutas y especias, madurado en barricas de roble.",
    },
    {
        nombre: "BenRiach 10",
        precio: 12000,
        stock: 85,
        codigo: "BR10",
        descripcion: "Un whisky escocés con notas de miel, frutas maduras y un toque de especias, madurado en barricas de bourbon.",
    },
    {
        nombre: "Glenmorangie Original 10",
        precio: 9500,
        stock: 110,
        codigo: "GM10",
        descripcion: "Un whisky suave y afrutado con notas de melaza, cítricos y vainilla, madurado en barricas de bourbon.",
    },
    {
        nombre: "Johnnie Walker Black Label",
        precio: 7800,
        stock: 100,
        codigo: "JWBL",
        descripcion: "Un blended Scotch whisky con un sabor robusto, equilibrado y notas de frutas secas y especias.",
    },
    {
        nombre: "Chivas Regal 12",
        precio: 8800,
        stock: 90,
        codigo: "CR12",
        descripcion: "Un blended Scotch whisky con notas de miel, frutas y un toque de roble, suave y accesible.",
    },
    {
        nombre: "Bushmills Original",
        precio: 6500,
        stock: 70,
        codigo: "BO",
        descripcion: "Un whisky irlandés con un perfil suave y notas de vainilla, miel y un toque de madera.",
    },
    {
        nombre: "GlenDronach 12",
        precio: 13500,
        stock: 65,
        codigo: "GD12",
        descripcion: "Madurado en barricas de jerez, con un sabor profundo y notas de frutas secas, especias y roble.",
    },
    {
        nombre: "Glenfarclas 15",
        precio: 15000,
        stock: 45,
        codigo: "GF15",
        descripcion: "Ofrece un perfil rico y complejo con notas de frutas secas, miel y especias, madurado en barricas de jerez.",
    },
    {
        nombre: "Aberlour 12",
        precio: 14000,
        stock: 55,
        codigo: "AB12",
        descripcion: "Un whisky con una mezcla equilibrada de dulzura y especias, madurado en barricas de jerez y bourbon.",
    },
    {
        nombre: "Talisker 10",
        precio: 11500,
        stock: 50,
        codigo: "T10",
        descripcion: "Un whisky isleño con un perfil ahumado, salino y especiado, con notas de frutas y especias.",
    },
    {
        nombre: "Glen Grant 10",
        precio: 10500,
        stock: 80,
        codigo: "GG10",
        descripcion: "Ofrece un sabor ligero y afrutado con notas de pera, manzana y un toque de roble.",
    },
    {
        nombre: "The Glenlivet 18",
        precio: 24500,
        stock: 30,
        codigo: "GL18",
        descripcion: "Un whisky madurado en barricas de roble y jerez, con un perfil complejo de frutas secas, miel y especias.",
    },
    {
        nombre: "Laphroaig 10",
        precio: 17000,
        stock: 60,
        codigo: "LP10",
        descripcion: "Conocido por su intenso sabor ahumado y turba, con notas de sal marina y especias.",
    },
    {
        nombre: "Glenrothes 12",
        precio: 14000,
        stock: 75,
        codigo: "GR12",
        descripcion: "Un whisky madurado en barricas de jerez con notas de frutas secas, especias y un toque de roble.",
    },
    {
        nombre: "Glenfiddich 15",
        precio: 13500,
        stock: 50,
        codigo: "GF15",
        descripcion: "Ofrece notas complejas de miel, frutas y especias, madurado en barricas de roble y jerez.",
    },
    {
        nombre: "Springbank 10",
        precio: 15500,
        stock: 40,
        codigo: "SP10",
        descripcion: "Un whisky con un perfil robusto de malta y notas de frutas, especias y un toque de humo.",
    },
    {
        nombre: "Aberfeldy 12",
        precio: 11000,
        stock: 85,
        codigo: "AF12",
        descripcion: "Un whisky dulce y afrutado con notas de miel, vainilla y un toque de roble.",
    },
    {
        nombre: "Knappogue Castle 12",
        precio: 12500,
        stock: 65,
        codigo: "KC12",
        descripcion: "Un whisky irlandés con un perfil suave y notas de vainilla, manzana verde y un toque de roble.",
    },
    {
        nombre: "Glenlivet 21",
        precio: 28000,
        stock: 20,
        codigo: "GL21",
        descripcion: "Un whisky añejo con un perfil rico de frutas secas, especias y un toque de roble, madurado en barricas de jerez.",
    },
];

export default bebidas;